export default {
  outputPath: './dist/output-tests/',
  inputPath: './conformance-tests',
  excludeFiles: [
    // ---- Milestone 1 ----
    'conformance-tests/base-types/strings/template-escape-new-line.js',
    'conformance-tests/base-types/strings/escape-sequences.js',
    'conformance-tests/base-types/strings/hex-escape-sequences.js',
    'conformance-tests/base-types/strings/octal-escape-sequence-follow-by-8.js',
    'conformance-tests/base-types/strings/octal-escape-sequences.js',
    'conformance-tests/structural-types/object/single-false-key-to-boolean.js',

    // ---- Milestone 2 ----
    'conformance-tests/expressions/call/method-expression-string_m2.js',
    'conformance-tests/expressions/call/method-expression_m2.js',
    'conformance-tests/expressions/call/method-react-create-div-element_m2.js',
    'conformance-tests/expressions/call/method-nested_m2.js',
    'conformance-tests/expressions/call/method-to-string_m2.js',
    'conformance-tests/expressions/call/method-to-string-nested_m2.js',
    'conformance-tests/expressions/call/method_m2.js',

    'conformance-tests/complex/simple-react-component_m2.js',

    // ---- Milestone 3 ----
    'conformance-tests/operators/relational/greater-equal-than/0_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/1_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/2_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/3_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/4_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/5_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/6_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/7_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/8_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/9_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/10_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/11_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/12_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/13_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/14_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/15_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/16_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/17_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/18_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/19_m3x.js',
    'conformance-tests/operators/relational/greater-equal-than/20_m3.js',
    'conformance-tests/operators/relational/greater-equal-than/21_m3.js',

    'conformance-tests/operators/relational/greater-than/0_m3.js',
    'conformance-tests/operators/relational/greater-than/1_m3.js',
    'conformance-tests/operators/relational/greater-than/2_m3.js',
    'conformance-tests/operators/relational/greater-than/3_m3x.js',
    'conformance-tests/operators/relational/greater-than/4_m3x.js',
    'conformance-tests/operators/relational/greater-than/5_m3x.js',
    'conformance-tests/operators/relational/greater-than/6_m3x.js',
    'conformance-tests/operators/relational/greater-than/7_m3x.js',
    'conformance-tests/operators/relational/greater-than/8_m3x.js',
    'conformance-tests/operators/relational/greater-than/9_m3x.js',
    'conformance-tests/operators/relational/greater-than/10_m3.js',
    'conformance-tests/operators/relational/greater-than/11_m3.js',
    'conformance-tests/operators/relational/greater-than/12_m3.js',
    'conformance-tests/operators/relational/greater-than/13_m3x.js',
    'conformance-tests/operators/relational/greater-than/14_m3x.js',
    'conformance-tests/operators/relational/greater-than/15_m3x.js',
    'conformance-tests/operators/relational/greater-than/16_m3x.js',
    'conformance-tests/operators/relational/greater-than/17_m3x.js',
    'conformance-tests/operators/relational/greater-than/18_m3x.js',
    'conformance-tests/operators/relational/greater-than/19_m3x.js',
    'conformance-tests/operators/relational/greater-than/20_m3x.js',
    'conformance-tests/operators/relational/greater-than/21_m3.js',
    'conformance-tests/operators/relational/greater-than/22_m3.js',

    'conformance-tests/operators/relational/less-equal-than/0_m3.js',
    'conformance-tests/operators/relational/less-equal-than/1_m3.js',
    'conformance-tests/operators/relational/less-equal-than/2_m3.js',
    'conformance-tests/operators/relational/less-equal-than/3_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/4_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/5_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/6_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/7_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/8_m3.js',
    'conformance-tests/operators/relational/less-equal-than/9_m3.js',
    'conformance-tests/operators/relational/less-equal-than/10_m3.js',
    'conformance-tests/operators/relational/less-equal-than/11_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/12_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/13_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/14_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/15_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/16_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/17_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/18_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/19_m3x.js',
    'conformance-tests/operators/relational/less-equal-than/20_m3.js',
    'conformance-tests/operators/relational/less-equal-than/21_m3.js',

    'conformance-tests/operators/relational/less-than/0_m3.js',
    'conformance-tests/operators/relational/less-than/1_m3.js',
    'conformance-tests/operators/relational/less-than/2_m3.js',
    'conformance-tests/operators/relational/less-than/3_m3x.js',
    'conformance-tests/operators/relational/less-than/4_m3x.js',
    'conformance-tests/operators/relational/less-than/5_m3x.js',
    'conformance-tests/operators/relational/less-than/6_m3x.js',
    'conformance-tests/operators/relational/less-than/7_m3x.js',
    'conformance-tests/operators/relational/less-than/8_m3x.js',
    'conformance-tests/operators/relational/less-than/9_m3x.js',
    'conformance-tests/operators/relational/less-than/10_m3.js',
    'conformance-tests/operators/relational/less-than/11_m3.js',
    'conformance-tests/operators/relational/less-than/12_m3.js',
    'conformance-tests/operators/relational/less-than/13_m3x.js',
    'conformance-tests/operators/relational/less-than/14_m3x.js',
    'conformance-tests/operators/relational/less-than/15_m3x.js',
    'conformance-tests/operators/relational/less-than/16_m3x.js',
    'conformance-tests/operators/relational/less-than/17_m3x.js',
    'conformance-tests/operators/relational/less-than/18_m3x.js',
    'conformance-tests/operators/relational/less-than/19_m3x.js',
    'conformance-tests/operators/relational/less-than/20_m3x.js',
    'conformance-tests/operators/relational/less-than/21_m3.js',
    'conformance-tests/operators/relational/less-than/22_m3.js',

    'conformance-tests/operators/relational/equality/0_m3.js',
    'conformance-tests/operators/relational/equality/1_m3.js',
    'conformance-tests/operators/relational/equality/2_m3.js',
    'conformance-tests/operators/relational/equality/3_m3.js',
    'conformance-tests/operators/relational/equality/4_m3.js',
    'conformance-tests/operators/relational/equality/5_m3.js',
    'conformance-tests/operators/relational/equality/6_m3.js',
    'conformance-tests/operators/relational/equality/7_m3.js',
    'conformance-tests/operators/relational/equality/8_m3.js',
    'conformance-tests/operators/relational/equality/9_m3.js',
    'conformance-tests/operators/relational/equality/10_m3.js',
    'conformance-tests/operators/relational/equality/object_m3.js',

    'conformance-tests/operators/relational/inequality/0_m3.js',
    'conformance-tests/operators/relational/inequality/1_m3.js',
    'conformance-tests/operators/relational/inequality/2_m3.js',
    'conformance-tests/operators/relational/inequality/3_m3.js',
    'conformance-tests/operators/relational/inequality/4_m3.js',
    'conformance-tests/operators/relational/inequality/5_m3.js',
    'conformance-tests/operators/relational/inequality/6_m3.js',
    'conformance-tests/operators/relational/inequality/7_m3.js',
    'conformance-tests/operators/relational/inequality/8_m3.js',
    'conformance-tests/operators/relational/inequality/9_m3.js',
    'conformance-tests/operators/relational/inequality/10_m3.js',
    'conformance-tests/operators/relational/inequality/object_m3.js',

    'conformance-tests/operators/relational/strict-equality/0_m3.js',
    'conformance-tests/operators/relational/strict-equality/1_m3.js',
    'conformance-tests/operators/relational/strict-equality/2_m3.js',
    'conformance-tests/operators/relational/strict-equality/3_m3.js',
    'conformance-tests/operators/relational/strict-equality/4_m3.js',
    'conformance-tests/operators/relational/strict-equality/5_m3.js',
    'conformance-tests/operators/relational/strict-equality/6_m3.js',
    'conformance-tests/operators/relational/strict-equality/7_m3.js',
    'conformance-tests/operators/relational/strict-equality/8_m3.js',
    'conformance-tests/operators/relational/strict-equality/9_m3.js',
    'conformance-tests/operators/relational/strict-equality/10_m3.js',

    'conformance-tests/operators/relational/strict-inequality/0_m3.js',
    'conformance-tests/operators/relational/strict-inequality/1_m3.js',
    'conformance-tests/operators/relational/strict-inequality/2_m3.js',
    'conformance-tests/operators/relational/strict-inequality/3_m3.js',
    'conformance-tests/operators/relational/strict-inequality/4_m3.js',
    'conformance-tests/operators/relational/strict-inequality/5_m3.js',
    'conformance-tests/operators/relational/strict-inequality/6_m3.js',
    'conformance-tests/operators/relational/strict-inequality/7_m3.js',
    'conformance-tests/operators/relational/strict-inequality/8_m3.js',
    'conformance-tests/operators/relational/strict-inequality/9_m3.js',
    'conformance-tests/operators/relational/strict-inequality/10_m3.js',
  ],
};
