-- ROBLOX upstream: https://github.com/Roblox/js-to-lua/blob/sha/conformance-tests/expressions/call/special-cases/jest-expect-methods_m5.js
jestExpect.any()
jestExpect.arrayContaining()
jestExpect.assertions(4)
jestExpect.closeTo(value)
jestExpect.hasAssertions()
jestExpect.objectContaining(value)
jestExpect.stringContaining(value)
jestExpect.stringMatching(value)
jestExpect.addSnapshotSerializer(mySerializer)
