-- ROBLOX upstream: https://github.com/Roblox/js-to-lua/blob/sha/conformance-tests/ts-types/luau-globals-string-keys_m5.ts
type Foo = {
	assert: boolean,
	collectgarbage: boolean,
	coroutine: boolean,
	debug: boolean,
	error: boolean,
	gcinfo: boolean,
	getfenv: boolean,
	getmetatable: boolean,
	io: boolean,
	ipairs: boolean,
	loadstring: boolean,
	math: boolean,
	newproxy: boolean,
	next: boolean,
	os: boolean,
	pairs: boolean,
	pcall: boolean,
	print: boolean,
	rawequal: boolean,
	rawget: boolean,
	rawset: boolean,
	require: boolean,
	select: boolean,
	setfenv: boolean,
	setmetatable: boolean,
	string: boolean,
	table: boolean,
	tonumber: boolean,
	tostring: boolean,
	type: boolean,
	unpack: boolean,
	xpcall: boolean,
	_G: boolean,
	_VERSION: boolean,
}
