-- ROBLOX upstream: https://github.com/Roblox/js-to-lua/blob/sha/conformance-tests/ts-types/reserved-keyword-string-keys_m5.ts
type Bar = {
	["and"]: boolean,
	["break"]: boolean,
	["do"]: boolean,
	["else"]: boolean,
	["elseif"]: boolean,
	["end"]: boolean,
	["false"]: boolean,
	["for"]: boolean,
	["function"]: boolean,
	["if"]: boolean,
	["in"]: boolean,
	["local"]: boolean,
	["nil"]: boolean,
	["not"]: boolean,
	["or"]: boolean,
	["repeat"]: boolean,
	["return"]: boolean,
	["then"]: boolean,
	["true"]: boolean,
	["until"]: boolean,
	["while"]: boolean,
}
