name: Fast Follow
description: 'Run fast follow tool on a target repository'

inputs:
  github-token:
    description: 'GitHub API token'
    required: true
  repo-path:
    description: 'Path to a target repository directory'
    required: true
  slack-channel-id:
    description: 'Slack channel id'
    required: false
  slack-signing-secret:
    description: 'Signing secret of the Slack App'
    required: false
  slack-bot-token:
    description: 'Token of the Slack bot account'
    required: false
  slack-app-token:
    description: 'Slack app API token'
    required: false
  pr-description-cc-users:
    description: 'Comma separated GitHub user names which start with @ (e.g. "@foo,@bar"). They will be mentioned in created PR description.'
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: roblox/js-to-lua
        fetch-depth: 0
        path: js-to-lua-build
        token: ${{inputs.github-token}}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.16.0'
        registry-url: https://npm.pkg.github.com/
        scope: '@roblox'
        cache: npm
        cache-dependency-path: js-to-lua-build/package-lock.json

    - name: Install dependencies
      working-directory: js-to-lua-build
      run: npm i
      shell: bash

    - name: Install wasm-pack
      shell: bash
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build Fast Follow
      working-directory: js-to-lua-build
      shell: bash
      run: |
        npx nx run upstream-utils:build
        npx nx run release-tracker:build
        npx nx run version-manager:build
        npx nx run diff-tool:build
        npx nx run fast-follow:build

    - name: Link Release Tracker
      shell: bash
      working-directory: js-to-lua-build/dist/libs/release-tracker
      run: npm link

    - name: Link Version Manager
      shell: bash
      working-directory: js-to-lua-build/dist/libs/version-manager
      run: npm link

    - name: Link Diff Tool
      shell: bash
      working-directory: js-to-lua-build/dist/libs/diff-tool
      run: npm link

    - name: Link Upstream Utils
      shell: bash
      working-directory: js-to-lua-build/dist/libs/upstream-utils
      run: npm link

    - name: Link Fast Follow
      shell: bash
      working-directory: js-to-lua-build/dist/libs/fast-follow
      run: |
        npm link @roblox/version-manager @roblox/release-tracker @roblox/diff-tool @js-to-lua/upstream-utils
        npm link

    - name: Link Release Tracker (root)
      shell: bash
      run: npm link @roblox/version-manager @roblox/release-tracker @roblox/diff-tool @js-to-lua/upstream-utils

    - name: Run Fast Follow
      shell: bash
      run: npx fast-follow upgrade ${{inputs.repo-path}} ${{ inputs.slack-channel-id && format('-c {0}', inputs.slack-channel-id)}} ${{ inputs.pr-description-cc-users && format('--prCC "{0}"', inputs.pr-description-cc-users)}}
      env:
        SLACK_SIGNING_SECRET: ${{ inputs.slack-signing-secret }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_APP_TOKEN: ${{ inputs.slack-app-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
